# Generated by Django 5.0.6 on 2024-07-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_organizer_id_participant_attendee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='pdfFile',
            field=models.FileField(default='default.pdf', upload_to='welcomeFile'),
        ),
    ]
